environment:
  # Nuxt requires node v8 minimum
  nodejs_version: "8"
  # Encrypt sensitive data (https://ci.appveyor.com/tools/encrypt)
  github_access_token:
    secure: b605ffb95c28482d38828e66629a47608860fb88
  github_email:
    secure: ff+vq0UmAYoZmAI880dZL9BM/xopt8ciynR7/jWViJQ=

# Only run on master branch
branches:
  only:
  - master

# Install scripts. (runs after repo cloning)
install:
  # switch nodejs version
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
  # generate static files
  - npm run generate
  # configure global git credentials store (https://www.appveyor.com/docs/how-to/git-push/)
  - git config --global credential.helper store

  - git config --global user.email $env:github_email
  # deploy to GitHub pages
  

# No tests to run
test: off

# Don't actually build.
build: off